### ISSUE TITLE
A new business rule is required

### ISSUE THREAD

**Issue by cmonsalvec** [carmsanc/ISII-WORKSHOPS-MAPA_VIRTUAL#2]
**Is your feature request related to a problem? Please describe.**

This feature is not related to a problem. It is related to a new policy of the organization. 

Based on the impact of the pandemic in the 2020 results, the board of the company has approved a new business rule (policy) beginning january 2021, that needs to be included in our product. 

**Describe the solution you'd like**

The new business rule establishes: If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.

Therefore, we ask you to modify the premium calculation adding this new rule. 

**Describe alternatives you've considered**

There is no alternative to be considered.

**Additional context**

I will provide you with more information if needed

Best regards,

**Comment by carmsanc** [comment]
The description of the new rule was understood and has been accepted.

**Comment by carmsanc** [comment]
Issue categorization step.

**Comment by carmsanc** [comment]
We will proceed to process the request @JavierAnchundia will be the assigned analyst and will perform the tests, @bryantutiven2  will develop the solution.

**Comment by JavierAnchundia** [comment]
The impact analysis has been performed 
[Impact Analysis.xlsx](https://github.com/carmsanc/ISII-WORKSHOPS-MAPA_VIRTUAL/files/5834927/Impact.Analysis.xlsx)

**Comment by JavierAnchundia** [comment]
@cmonsalvec , do you agree with the estimate and resources required to make the requested change?

**Comment by cmonsalvec** [comment]
Dear @JavierAnchundia  yes, I agree with the time and resources required. I will sign the analysis document next time I will pass by your office, please continue with the development.

**Comment by JavierAnchundia** [comment]
Thank you very much @cmonsalvec , we will keep you informed

**Comment by bryantutiven2** [comment]
jbkvkdfvbk

**Comment by bryantutiven2** [comment]
A new policy associated with the calculation of the premium was added as requested by the client.

https://github.com/carmsanc/ISII-WORKSHOPS-MAPA_VIRTUAL/blob/0c2e2f5a91f3a463b9330a8949a028286fa6dc35/ec.edu.espol.workshops.second/src/main/java/ec/edu/espol/workshops/second/PremiumCalculation.java#L17-L19

**Comment by JavierAnchundia** [comment]
Dear @cmonsalvec , we already performed the test plan . Here you will find the document with the results. 
[Test Plan.xlsx](https://github.com/carmsanc/ISII-WORKSHOPS-MAPA_VIRTUAL/files/5847037/Test.Plan.xlsx)

**Comment by JavierAnchundia** [comment]
We submit the acceptance test plan for your review and in case you agree, please let us know. Thank you @cmonsalvec .
[Acceptance Testing.xlsx](https://github.com/carmsanc/ISII-WORKSHOPS-MAPA_VIRTUAL/files/5847052/Acceptance.Testing.xlsx)

**Comment by cmonsalvec** [comment]
Dear @JavierAnchundia thanks, I wonder if all these test cases cover all the possible paths in the new code

**Comment by JavierAnchundia** [comment]
Good morning @cmonsalvec . Yes, effectively, it cover all the possible paths in the new code. I attach the images of the analysis performed. The first image is the Branch Coverage, the second is the Path Coverage and the third is Statement Coverage. The last image is the DD-path graph
![Branch Covarege](https://user-images.githubusercontent.com/33844585/105377703-1ac3c300-5bd9-11eb-860d-6dc7416759c8.png)
![Path Coverage](https://user-images.githubusercontent.com/33844585/105377709-1b5c5980-5bd9-11eb-84e7-3b7a30ec8c8e.png)
![Statement Coverage](https://user-images.githubusercontent.com/33844585/105377711-1bf4f000-5bd9-11eb-8976-37631aba27d3.png)
![Structural Testing](https://user-images.githubusercontent.com/33844585/105377714-1bf4f000-5bd9-11eb-8267-fc2a991733e2.png)

**Comment by cmonsalvec** [comment]
Dear @JavierAnchundia ,

Great, in that case I agree with the test plan. Please perform the test cases and let me know the results.

Regards,

**Comment by JavierAnchundia** [comment]
Dear @cmonsalvec , here we attached the Pass/Fail column of the Test Plan. All the tests have successfully passed.
[Test Plan Results.xlsx](https://github.com/carmsanc/ISII-WORKSHOPS-MAPA_VIRTUAL/files/5851113/Test.Plan.Results.xlsx)

**Comment by cmonsalvec** [comment]
Excelent @JavierAnchundia , glad to see all the tests passed. I'm happy with this.

**Comment by carmsanc** [comment]
As mentioned before all tests have been performed, and all the required documentation is complete. Therefore, we inform you that the solution is complete @cmonsalvec and @bryantutiven2 will release the new software version.

**Comment by cmonsalvec** [comment]
Thanks @carmsanc , i will wait for @bryantutiven2  instructions

**Comment by bryantutiven2** [comment]
Good afternoon @cmonsalvec, instructions are attached to test the new version of the software
[versionSotwareDocument.pdf](https://github.com/carmsanc/ISII-WORKSHOPS-MAPA_VIRTUAL/files/5852355/versionSotwareDocument.pdf)

**Comment by cmonsalvec** [comment]
Dear @bryantutiven2 ,

Great, they are very clear. I am sure my organization will be able to use the solution.

**Comment by carmsanc** [comment]
Dear @cmonsalvec , please let us know if you have satisfactorily used the solution, or if you weren't able to use the new version so we can fix the software.

**Comment by cmonsalvec** [comment]
Dear @carmsanc 

So far the new version of the product is working really good, my organization is very happy with this.

**Comment by carmsanc** [comment]
We are glad the solution is working for you. We will keep in touch, thank you!
